import { StyleSheet } from 'react-native';
import { LIME_GREEN } from '../constants/mapColors';

export const getStyles = (colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: 'transparent' },
  // "Nevoeiro" sobre a imagem de fundo: aumenta o valor de opacity (0 a 1) para esconder mais a imagem,
  // ou diminui para deixá-la mais visível. Podes também trocar a cor (ex: '#ffffff' para um nevoeiro claro).
  backgroundFogOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: '#000000', opacity: 0.45 },
  scrollContent: { padding: 16, paddingTop: 48, paddingBottom: 24 },
  activeExerciseScroll: { padding: 20, paddingTop: 36, paddingBottom: 40 },
  appHeaderTitle: { fontSize: 26, fontWeight: '900', color: colors.COLOR_PRIMARY, textAlign: 'center', marginBottom: 20, marginTop: 16, letterSpacing: 2, textShadowColor: 'rgba(0,0,0,0.25)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  // Frase motivacional que ocupa o lugar onde estava o título (ver MotivationalQuote.js).
  // fontSize é o tamanho MÁXIMO (frases de uma linha ficam com este); adjustsFontSizeToFit
  // no componente encolhe automaticamente as frases mais compridas até caberem em 2 linhas.
  motivationalQuoteText: { fontSize: 30, fontWeight: '900', color: '#ffffff', textAlign: 'center', marginBottom: 24, marginTop: 8, letterSpacing: -0.5, lineHeight: 34, textTransform: 'uppercase' },
  mapContainer: { height: 220, borderRadius: 16, overflow: 'hidden', marginBottom: 14, borderWidth: 1, borderColor: colors.COLOR_DIVIDER, backgroundColor: '#061414' },
  map: { flex: 1, backgroundColor: 'transparent' },
  bentoHeroCardPrimary: { backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 20, padding: 18, marginBottom: 12, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  cardHeaderLeftRow: { flexDirection: 'row', alignItems: 'center' },
  tileNumberLight: { color: colors.COLOR_LIME_ENERGY, fontWeight: '800', fontSize: 16, marginRight: 8 },
  cardHeaderTitleLight: { color: '#FFFFFF', fontWeight: '700', fontSize: 14, letterSpacing: 1 },
  statusDotTouchable: { padding: 6 },
  statusDotDark: { width: 12, height: 12, borderRadius: 6 },
  recommendationTextLight: { color: '#E2E8F0', fontSize: 16, fontWeight: '600', marginBottom: 14 },
  // Botão "Iniciar Corrida" da sessão recomendada: verde-lima fixo (pedido
  // explícito), não segue o esquema de cores como o resto dos botões "Light".
  actionBtnLight: { backgroundColor: LIME_GREEN, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  actionBtnTextDark: { color: colors.COLOR_ACCENT_TEXT, fontWeight: '800', fontSize: 13, letterSpacing: 1 },
  bentoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  bentoTileSage: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 20, padding: 16, width: '48%', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  bentoTileSecondary: { backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 20, padding: 16, width: '48%', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  tileNumberPrimary: { color: colors.COLOR_SECONDARY, fontWeight: '800', fontSize: 16, marginBottom: 4 },
  tileTitleDark: { color: colors.COLOR_PRIMARY, fontWeight: '800', fontSize: 15, marginBottom: 4 },
  tileSubDark: { color: colors.COLOR_SECONDARY, fontSize: 11, marginBottom: 12, lineHeight: 14 },
  tileActionTextDark: { color: colors.COLOR_PRIMARY, fontWeight: '700', fontSize: 11 },
  tileTitleLight: { color: '#FFFFFF', fontWeight: '800', fontSize: 15, marginBottom: 4 },
  tileSubLight: { color: '#CBD5E1', fontSize: 11, marginBottom: 12, lineHeight: 14 },
  tileActionTextLight: { color: colors.COLOR_LIME_ENERGY, fontWeight: '700', fontSize: 11 },
  activeBentoTileHighlight: { borderWidth: 2, borderColor: colors.COLOR_LIME_ENERGY },
  accordionBodyGrid: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 20, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  submenuHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.COLOR_DIVIDER, paddingBottom: 8 },
  submenuHeaderText: { color: colors.COLOR_PRIMARY, fontWeight: '800', fontSize: 12, letterSpacing: 1 },
  submenuCloseText: { color: colors.COLOR_SECONDARY, fontWeight: '700', fontSize: 11 },
  skipPhaseBtn: { marginTop: 12, backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 10, paddingVertical: 10, alignItems: 'center', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  skipPhaseBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 12, letterSpacing: 1 },
  itemBtn: { backgroundColor: colors.COLOR_BG_MAIN, padding: 12, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  itemBtnText: { color: colors.COLOR_PRIMARY, fontWeight: '600', fontSize: 13 },
  itemBtnSubText: { color: colors.COLOR_SECONDARY, fontWeight: '600', fontSize: 11, marginTop: 4 },
  levelCard: { backgroundColor: colors.COLOR_BG_MAIN, borderRadius: 12, marginBottom: 8, overflow: 'hidden', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  levelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12 },
  levelHeaderActive: { backgroundColor: colors.COLOR_DIVIDER },
  levelTitleRow: { flexDirection: 'row', alignItems: 'center' },
  currentDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.COLOR_PRIMARY, marginRight: 6 },
  levelTitle: { fontWeight: '700', fontSize: 13, color: colors.COLOR_PRIMARY },
  levelTitleActiveText: { fontWeight: '900' },
  levelChevron: { fontSize: 11, color: colors.COLOR_SECONDARY, fontWeight: '700' },
  levelDetailsContainer: { padding: 12, paddingTop: 0 },
  levelSummaryText: { fontSize: 11, color: colors.COLOR_SECONDARY, marginBottom: 8, fontStyle: 'italic' },
  sessionList: { flexDirection: 'row', justifyContent: 'space-between' },
  sessBtn: { backgroundColor: colors.COLOR_CARD_BG, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 8, flex: 1, marginHorizontal: 2, alignItems: 'center', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  sessBtnDone: { backgroundColor: colors.COLOR_LIME_ENERGY },
  sessBtnRecommended: { borderColor: colors.COLOR_PRIMARY, borderWidth: 2 },
  sessBtnText: { fontSize: 11, fontWeight: '600', color: colors.COLOR_PRIMARY },
  sessBtnTextDone: { color: colors.COLOR_ACCENT_TEXT },
  sessBtnTextRecommended: { fontWeight: '800' },
  // Coluna que envolve cada botão de sessão + o seu "melhor tempo" por baixo,
  // sem alterar o espaçamento/alinhamento em linha que já existia (sessionList).
  sessBtnColumn: { flex: 1, marginHorizontal: 2 },
  sessBtnInColumn: { marginHorizontal: 0, width: '100%' },
  sessionBestTimeText: { fontSize: 9, fontWeight: '700', color: colors.COLOR_SECONDARY, textAlign: 'center', marginTop: 3 },
  // Texto de "melhor tempo" mostrado durante um exercício ativo (caminhadas/desafios).
  bestTimeText: { fontSize: 12, fontWeight: '700', color: colors.COLOR_SECONDARY, textAlign: 'center', marginTop: 4 },
  bestTimeHighlight: { color: colors.COLOR_PRIMARY, fontWeight: '900' },
  bentoHeroBottom: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 20, padding: 18, marginBottom: 12, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  cardHeaderTitleDark: { color: colors.COLOR_PRIMARY, fontWeight: '800', fontSize: 14, letterSpacing: 1 },
  recommendationTextDark: { color: colors.COLOR_SECONDARY, fontSize: 13, fontWeight: '600', marginTop: 4 },
  accordionIcon: { color: colors.COLOR_PRIMARY, fontWeight: '700', fontSize: 11 },
  historyCard: { backgroundColor: colors.COLOR_BG_MAIN, padding: 12, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  historyHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  historyTitle: { fontWeight: '700', fontSize: 13, color: colors.COLOR_PRIMARY },
  historySub: { fontSize: 11, color: colors.COLOR_SECONDARY },
  historyFailedBadge: {
    fontSize: 11,
    color: colors.COLOR_RED_ACCENT || '#ef4444',
    fontWeight: '700',
    marginTop: 2,
    marginBottom: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  emptyText: { color: colors.COLOR_SECONDARY, fontSize: 13, fontStyle: 'italic', textAlign: 'center', padding: 10 },
  batterySectionTouchable: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 20, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  batteryTitleRow: { marginBottom: 10 },
  batterySectionTitle: { color: colors.COLOR_PRIMARY, fontWeight: '800', fontSize: 12, letterSpacing: 1 },
  batteryContainer: { flexDirection: 'row', alignItems: 'center' },
  batteryBody: { flex: 1, height: 30, borderRadius: 7, borderWidth: 2, borderColor: colors.COLOR_DIVIDER, padding: 3 },
  batteryTrack: { flex: 1, borderRadius: 4, backgroundColor: colors.COLOR_DIVIDER, overflow: 'hidden' },
  batteryFill: { height: '100%', backgroundColor: colors.COLOR_LIME_ENERGY, borderRadius: 4 },
  batteryTerminal: { width: 6, height: 14, marginLeft: 2, borderTopRightRadius: 3, borderBottomRightRadius: 3, backgroundColor: colors.COLOR_DIVIDER },
  batteryCountText: { marginTop: 8, textAlign: 'center', color: colors.COLOR_SECONDARY, fontWeight: '700', fontSize: 12 },
  activeBtnRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  pauseBtn: { backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 14, padding: 16, flex: 1, marginRight: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  pauseBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 14, letterSpacing: 1 },
  cancelBtn: { backgroundColor: colors.COLOR_RED_ACCENT, borderRadius: 14, padding: 16, width: 120, alignItems: 'center' },
  cancelBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 14, letterSpacing: 1 },
  bentoGridActive: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 12 },
  bentoCardActive: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 16, padding: 14, width: '48%', marginBottom: 10, borderWidth: 1, borderColor: colors.COLOR_DIVIDER, alignItems: 'center' },
  bentoFinishCard: { backgroundColor: '#22c55e', borderColor: '#22c55e', justifyContent: 'center' },
  bentoFinishCardText: { color: '#FFFFFF', fontWeight: '900', fontSize: 13, textAlign: 'center', letterSpacing: 0.5, lineHeight: 17 },
  metricLabel: { color: colors.COLOR_SECONDARY, fontSize: 10, fontWeight: '800', letterSpacing: 1, marginBottom: 4 },
  metricValue: { color: colors.COLOR_PRIMARY, fontSize: 18, fontWeight: '900' },
  headerContainerActive: { alignItems: 'center', marginBottom: 16 },
  activeTitle: { fontSize: 20, fontWeight: '900', color: colors.COLOR_PRIMARY, textAlign: 'center' },
  rockportProgressCard: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 16, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  rockportHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  rockportLabel: { color: colors.COLOR_PRIMARY, fontWeight: '800', fontSize: 11, letterSpacing: 1 },
  rockportValue: { color: colors.COLOR_SECONDARY, fontWeight: '700', fontSize: 11 },
  progressBarBackground: { height: 8, backgroundColor: colors.COLOR_DIVIDER, borderRadius: 4, overflow: 'hidden', marginBottom: 8 },
  progressBarFill: { height: '100%', backgroundColor: colors.COLOR_LIME_ENERGY, borderRadius: 4 },
  recordHighlightBox: { backgroundColor: colors.COLOR_BG_MAIN, padding: 8, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  recordTitle: { color: colors.COLOR_SECONDARY, fontSize: 10, fontWeight: '700' },
  recordValue: { color: colors.COLOR_PRIMARY, fontSize: 12, fontWeight: '800' },
  timelineWrapper: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 16, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  phaseHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  currentPhaseText: { color: colors.COLOR_PRIMARY, fontWeight: '900', fontSize: 13, letterSpacing: 1 },
  phaseCountdownText: { color: colors.COLOR_SECONDARY, fontWeight: '800', fontSize: 14 },
  segmentedProgressBarContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', height: 12 },
  singlePhaseBarSegmentWrapper: { flex: 1, flexDirection: 'row', alignItems: 'center', height: '100%', paddingHorizontal: 1 },
  singlePhaseBarSegment: { flex: 1, height: 6, borderRadius: 3 },
  singlePhaseBarCurrentActive: { height: 10 },
  segmentDividerLine: { width: 1, height: 4, backgroundColor: '#FFFFFF' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalCard: { backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 20, padding: 20, width: '100%', maxWidth: 340, borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  modalTitle: { fontSize: 16, fontWeight: '900', color: '#FFFFFF', marginBottom: 10, textAlign: 'center' },
  modalText: { fontSize: 13, color: '#FFFFFF', lineHeight: 18, marginBottom: 16, textAlign: 'center' },
  modalBtn: { backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 12, padding: 12, alignItems: 'center' },
  modalBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 13, letterSpacing: 1 },
  testResultInput: {
    borderWidth: 1,
    borderColor: colors.COLOR_DIVIDER,
    borderRadius: 12,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: 10,
    marginBottom: 14,
  },
  testResultHighlight: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.COLOR_LIME_ENERGY,
    textAlign: 'center',
    marginBottom: 10,
  },
  esquinaCard: { backgroundColor: colors.COLOR_CARD_BG, borderRadius: 20, padding: 20, width: '100%', maxWidth: 340, borderWidth: 1, borderColor: colors.COLOR_DIVIDER, alignItems: 'center' },
  esquinaTitle: { fontSize: 18, fontWeight: '900', color: '#FFFFFF', marginBottom: 10, textAlign: 'center' },
  esquinaText: { fontSize: 13, color: '#FFFFFF', lineHeight: 18, marginBottom: 20, textAlign: 'center' },
  esquinaYesBtn: { backgroundColor: colors.COLOR_LIME_ENERGY, borderRadius: 12, padding: 14, width: '100%', alignItems: 'center', marginBottom: 10 },
  esquinaYesBtnText: { color: colors.COLOR_ACCENT_TEXT, fontWeight: '900', fontSize: 13, letterSpacing: 1 },
  esquinaNoBtn: { backgroundColor: colors.COLOR_PRIMARY_BG, borderRadius: 12, padding: 14, width: '100%', alignItems: 'center' },
  esquinaNoBtnText: { color: '#FFFFFF', fontWeight: '900', fontSize: 13, letterSpacing: 1 },
  sectionSubTitle: { color: colors.COLOR_PRIMARY, fontWeight: '800', fontSize: 12, letterSpacing: 1, marginBottom: 10, marginTop: 4 },
  sliderLabelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  sliderValueText: { color: colors.COLOR_PRIMARY, fontWeight: '900', fontSize: 13 },
  sliderTrackWrapper: { justifyContent: 'center', height: 30, marginBottom: 4 },
  sliderTrackBg: { height: 6, borderRadius: 3, backgroundColor: colors.COLOR_DIVIDER, overflow: 'hidden' },
  sliderTrackFill: { height: '100%', backgroundColor: colors.COLOR_LIME_ENERGY, borderRadius: 3 },
  sliderThumb: { position: 'absolute', width: 22, height: 22, borderRadius: 11, marginLeft: -11, top: 4, backgroundColor: colors.COLOR_PRIMARY_BG, borderWidth: 2, borderColor: colors.COLOR_LIME_ENERGY },
  themeSelectorContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 10 },
  themeBtn: { backgroundColor: colors.COLOR_BG_MAIN, borderRadius: 10, padding: 10, width: '48%', marginBottom: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.COLOR_DIVIDER },
  themeBtnActive: { borderColor: colors.COLOR_PRIMARY, borderWidth: 2, backgroundColor: colors.COLOR_CARD_BG },
  themeBtnText: { fontSize: 10, fontWeight: '700', color: colors.COLOR_PRIMARY, marginTop: 4 },
  themeBtnTextActive: { fontWeight: '900' },
  inputLabel: { fontSize: 11, fontWeight: '700', color: colors.COLOR_SECONDARY, marginBottom: 4 },
  input: { backgroundColor: colors.COLOR_BG_MAIN, borderWidth: 1, borderColor: colors.COLOR_DIVIDER, borderRadius: 10, padding: 10, fontSize: 13, color: colors.COLOR_PRIMARY, marginBottom: 10 },
  divider: { height: 1, backgroundColor: colors.COLOR_DIVIDER, marginVertical: 14 },
  dangerBtn: { backgroundColor: colors.COLOR_RED_ACCENT, borderRadius: 12, padding: 12, alignItems: 'center', marginTop: 6 },
  dangerBtnText: { color: '#FFFFFF', fontWeight: '800', fontSize: 12, letterSpacing: 1 }
});
