// Frases motivacionais mostradas no ecrã principal, no lugar onde estava o
// título da app. Uma frase por abertura da app (ver MotivationalQuote.js),
// avançando sequencialmente pela lista para garantir que todas vão sendo
// mostradas antes de repetir alguma.
export const MOTIVATIONAL_QUOTES = [
  "Just one foot in front of the other.",
  "Stop thinking and just do it.",
  "The miracle is that you had the courage to start.",
  "Run into your unknown.",
  "Pain is temporary, pride is forever.",
  "Your legs are not giving up. Your head is giving up.",
  "What seems hard now will one day be your warm-up.",
  "It is supposed to be hard; the hard is what makes it great.",
  "You didn't get this far to only go this far.",
  "It's not only about the finish line.",
  "Pursue your personal best, not perfection.",
  "Even the worst run is better than no run at all.",
  "O obstáculo desaparece assim que dás o primeiro passo.",
  "A tua mente cria a barreira, as tuas pernas destroem-na.",
  "Chova ou faça sol, o teu compromisso é contigo.",
  "Esquece as desculpas. Foca-te no teu objetivo.",
  "O primeiro quilómetro é o mais difícil. Começa agora.",
  "Não penses no cansaço. Pensa em como te vais sentir depois.",
  "Vencer a preguiça inicial é a tua primeira vitória de hoje.",
  "Só custa até calçares as sapatilhas.",
  "Transforma as contrariedades na tua força de hoje.",
  "Deixa os problemas para trás a cada passada.",
  "O teu corpo aguenta. Só tens de convencer a tua mente.",
  "Hoje é o dia ideal para superares os teus limites.",
  "Menos desculpas, mais quilómetros.",
  "A cama está confortável, mas não te dá resultados.",
  "O teu cérebro está a mentir-te. Levanta-te.",
  "Ninguém quer saber do teu cansaço. Corre.",
  "A motivação falha. A disciplina não.",
  "Chover é apenas uma desculpa para os fracos.",
  "O teu futuro eu vai agradecer-te por não seres brando hoje.",
  "Não vieste aqui para desistir ao primeiro obstáculo.",
  "Se fosse fácil, toda a gente o fazia.",
  "Estás a queixar-te ou estás a correr?",
  "Engole o cansaço e calça as sapatilhas.",
  "O único obstáculo real és tu próprio.",
  "O teu ritmo hoje não importa, o que importa é estares aqui.",
  "Se o corpo estiver pesado, vai mais devagar. O importante é ir.",
  "Dá o teu melhor hoje, mesmo que seja apenas caminhar.",
  "Respira fundo. O primeiro passo é o único que custa.",
  "Deixa o peso do dia em cada quilómetro que ficas para trás.",
  "A corrida é o teu momento de paz. Cuida de ti.",
  "Usa este tempo para limpar a mente e recarregar o coração.",
  "O dia foi difícil? Deixa a estrada ouvir o teu desabafo.",
  "Já venceste a parte mais difícil: decidiste começar.",
  "Sê gentil contigo. Cada metro percorrido já é uma vitória.",
  "Tu és mais forte do que qualquer contrariedade.",
  "Corre por ti, pela tua saúde e pelo teu bem-estar.",
  "Encontra a tua força",
  "Não ligues ao que os outros dizem. Sê tu próprio.",
  "Be gentle with yourself, but show up anyway.",
  "Leave the weight of the day behind you.",
  "Any pace is a good pace. Just move.",
  "Your only competition is who you were yesterday.",
  "Listen to your body, but trust your strength.",
  "You made it to the starting line. That's the biggest win.",
];
