// Frases motivacionais mostradas no ecrã principal, no lugar onde estava o
// título da app. Uma frase por abertura da app (ver MotivationalQuote.js),
// avançando sequencialmente pela lista para garantir que todas vão sendo
// mostradas antes de repetir alguma.
export const MOTIVATIONAL_QUOTES = [
  "Just one foot in front of the other.",
  "Stop thinking and just do it.",
  "The miracle is that you had the courage to start.",
  "Run into your unknown.",
  "Pain is temporary, pride is forever.",
  "Your legs are not giving up. Your head is giving up.",
  "What seems hard now will one day be your warm-up.",
  "It is supposed to be hard; the hard is what makes it great.",
  "You didn't get this far to only go this far.",
  "It's not only about the finish line.",
  "Pursue your personal best, not perfection.",
  "Even the worst run is better than no run at all.",
  "O obstáculo desaparece assim que dás o primeiro passo.",
  "A tua mente cria a barreira, as tuas pernas destroem-na.",
  "Chova ou faça sol, o teu compromisso é contigo.",
  "Esquece as desculpas. Foca-te no teu objetivo.",
  "O primeiro quilómetro é o mais difícil. Começa agora.",
  "Não penses no cansaço. Pensa em como te vais sentir depois.",
  "Vencer a preguiça inicial é a tua primeira vitória de hoje.",
  "Só custa até calçares as sapatilhas.",
  "Transforma as contrariedades na tua força de hoje.",
  "Deixa os problemas para trás a cada passada.",
  "O teu corpo aguenta. Só tens de convencer a tua mente.",
  "Hoje é o dia ideal para superares os teus limites.",
  "Menos desculpas, mais quilómetros.",
  "A cama está confortável, mas não te dá resultados.",
  "O teu cérebro está a mentir-te. Levanta-te.",
  "Ninguém quer saber do teu cansaço. Corre.",
  "A motivação falha. A disciplina não.",
  "Chover é apenas uma desculpa para os fracos.",
  "O teu futuro eu vai agradecer-te por não seres brando hoje.",
  "Não vieste aqui para desistir ao primeiro obstáculo.",
  "Se fosse fácil, toda a gente o fazia.",
  "Estás a queixar-te ou estás a correr?",
  "Engole o cansaço e calça as sapatilhas.",
  "O único obstáculo real és tu próprio.",
  "O teu ritmo hoje não importa, o que importa é estares aqui.",
  "Se o corpo estiver pesado, vai mais devagar. O importante é ir.",
  "Dá o teu melhor hoje, mesmo que seja apenas caminhar.",
  "Respira fundo. O primeiro passo é o único que custa.",
  "Deixa o peso do dia em cada quilómetro que ficas para trás.",
  "A corrida é o teu momento de paz. Cuida de ti.",
  "Usa este tempo para limpar a mente e recarregar o coração.",
  "O dia foi difícil? Deixa a estrada ouvir o teu desabafo.",
  "Já venceste a parte mais difícil: decidiste começar.",
  "Sê gentil contigo. Cada metro percorrido já é uma vitória.",
  "Tu és mais forte do que qualquer contrariedade.",
  "Corre por ti, pela tua saúde e pelo teu bem-estar.",
  "Encontra a tua força",
  "Não ligues ao que os outros dizem. Sê tu próprio.",
  "Be gentle with yourself, but show up anyway.",
  "Leave the weight of the day behind you.",
  "Any pace is a good pace. Just move.",
  "Your only competition is who you were yesterday.",
  "Listen to your body, but trust your strength.",
  "You made it to the starting line. That's the biggest win.",

  "A derrota é temporária, desistir é permanente.",
  "O sucesso é o resultado de muita repetição e disciplina.",
  "Qualquer coisa que valha a pena fazer, será difícil.",
  "Treina a mente para suportar o desconforto; o sucesso é conquistado com esforço incansável.",
  "Dar menos do que o teu melhor é sacrificar um dom.",
  "Não precisas de ser rápido, só precisas de ir.",
  "Se queres correr, corre um quilómetro. Se queres experimentar outra vida, corre 5 km.",
  "Corre quando puderes, caminha se precisares, rasteja se for necessário, mas nunca desistas.",
  "Não penses no fim da corrida, foca-te apenas no passo que estás a dar agora.",
  "Cada quilómetro percorrido é uma vitória sobre a tua versão de ontem.",
  "O sucesso não acontece por acaso.",
  "Não sou o próximo Bolt ou Phelps, sou o primeiro Marco.",
  "Se te estás a calçar para sair de casa e ir correr, tu és um corredor.",
  "Quem move a montanha começa por carregar primeiro as pedras mais pequenas.",
  "Não acontece do dia para a noite, tens de treinar e acreditar em ti; isso sim é o mais importante.",
  "The body achieves what the mind believes.",
  "Discipline defeats excuses.",
  "Get 1% better every day.",
  "Pain is temporary, but pride is eternal.",
  "Train today to thank yourself tomorrow.",
  "hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.",
  "I've failed over and over and over again in my life. And that is why I succeed.",
  "There are people who don't see results in two months and they give up.",
  "Every step drops the weight; every mile builds the habit.",
  "It doesn’t matter how slow you run, you are still lapping everyone on the couch.",
  "Run for your health, the weight loss will follow.",
  "Don't run away from your weight; run towards your freedom.",
  "The hardest step for a runner is the first one out the door.",
  "You don't have to be fast. You just have to go.",
  "Your body can stand almost anything. It’s your mind that you have to convince.",
  "Progress is quiet. Keep moving, keep breathing, keep shedding the old you.",
  "Sweat is just fat crying. Keep pushing.",
  "Wake up with determination, come back with satisfaction.",
  "Beat the sun. Beat your excuses.",
  "Your fitness goals don't care how warm your bed is.",
  "You are only one run away from a good mood.",
  "Your body isn't tired from work; your mind is. Wake it up with a run.",
  "Don't sit on the couch first. Put your shoes on and go.",
  "Change your clothes, change your mindset.",
  "Action comes before motivation. Just step outside.",
  "You will never regret a run, but you will regret staying inside.",
  "It's not about having time; it's about making time.",
  "O mais difícil nunca é a corrida; é passar a porta de casa.",
  "If you can't fly, then run; if you can't run, then walk; if you can't walk, then crawl, but by all means keep moving.",
  "The secret of getting ahead is getting started.",
  "You don't have to see the whole staircase, just take the first step.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "There are many ways of going forward, but only one way of standing still.",
  "You don't drown by falling in the water; you drown by staying there.",
  "You're braver than you believe, and stronger than you seem, and smarter than you think.",
  "Doubt kills more dreams than failure ever will.",
  "Dá tempo ao tempo. Até o sol precisa de tempo para nascer e trazer o dia.",
  "O descanso também é uma forma de progresso. Respira, recupera forças e continua.",
  "És muito mais forte do que as dúvidas que tens na tua cabeça.",
  "Olha para trás e repara no caminho que já percorreste. Já superaste tanto.",
];
