// Frases motivacionais mostradas no ecrã principal, no lugar onde estava o
// título da app. Uma frase por abertura da app (ver MotivationalQuote.js),
// avançando sequencialmente pela lista para garantir que todas vão sendo
// mostradas antes de repetir alguma.
export const MOTIVATIONAL_QUOTES = [
  "Just one foot in front of the other.",
  "Stop thinking and just do it.",
  "The miracle is that you had the courage to start.",
  "Run into your unknown.",
  "Pain is temporary, pride is forever.",
  "Your legs are not giving up. Your head is giving up.",
  "What seems hard now will one day be your warm-up.",
  "It is supposed to be hard; the hard is what makes it great.",
  "You didn't get this far to only go this far.",
  "It's not only about the finish line.",
  "Pursue your personal best, not perfection.",
  "Even the worst run is better than no run at all.",
  "O obstáculo desaparece assim que dás o primeiro passo.",
  "A tua mente cria a barreira, as tuas pernas destroem-na.",
  "Chova ou faça sol, o teu compromisso é contigo.",
  "Esquece as desculpas. Foca-te no teu objetivo.",
  "O primeiro quilómetro é o mais difícil. Começa agora.",
  "Não penses no cansaço. Pensa em como te vais sentir depois.",
  "Vencer a preguiça inicial é a tua primeira vitória de hoje.",
  "Só custa até calçares as sapatilhas.",
  "Transforma as contrariedades na tua força de hoje.",
  "Deixa os problemas para trás a cada passada.",
  "O teu corpo aguenta. Só tens de convencer a tua mente.",
  "Hoje é o dia ideal para superares os teus limites.",
  "Menos desculpas, mais quilómetros.",
  "A cama está confortável, mas não te dá resultados.",
  "O teu cérebro está a mentir-te. Levanta-te.",
  "Ninguém quer saber do teu cansaço. Corre.",
  "A motivação falha. A disciplina não.",
  "Chover é apenas uma desculpa para os fracos.",
  "O teu futuro eu vai agradecer-te por não seres brando hoje.",
  "Não vieste aqui para desistir ao primeiro obstáculo.",
  "Se fosse fácil, toda a gente o fazia.",
  "Estás a queixar-te ou estás a correr?",
  "Engole o cansaço e calça as sapatilhas.",
  "O único obstáculo real és tu próprio.",
  "O teu ritmo hoje não importa, o que importa é estares aqui.",
  "Se o corpo estiver pesado, vai mais devagar. O importante é ir.",
  "Dá o teu melhor hoje, mesmo que seja apenas caminhar.",
  "Respira fundo. O primeiro passo é o único que custa.",
  "Deixa o peso do dia em cada quilómetro que ficas para trás.",
  "A corrida é o teu momento de paz. Cuida de ti.",
  "Usa este tempo para limpar a mente e recarregar o coração.",
  "O dia foi difícil? Deixa a estrada ouvir o teu desabafo.",
  "Já venceste a parte mais difícil: decidiste começar.",
  "Sê gentil contigo. Cada metro percorrido já é uma vitória.",
  "Tu és mais forte do que qualquer contrariedade.",
  "Corre por ti, pela tua saúde e pelo teu bem-estar.",
  "Encontra a tua força",
  "Não ligues ao que os outros dizem. Sê tu próprio.",
  "Be gentle with yourself, but show up anyway.",
  "Leave the weight of the day behind you.",
  "Any pace is a good pace. Just move.",
  "Your only competition is who you were yesterday.",
  "Listen to your body, but trust your strength.",
  "You made it to the starting line. That's the biggest win.",
  "A slow step beats a full stop.",
  "A wet walk clears a heavy mind.",
  "Break the routine. Break the mold. Step out.",
  "Change feels risky until staying the same feels worse.",
  "Change happens outside comfort zones.",
  "Change the way you look at things, and the things you look at change.",
  "Conquering the Elements",
  "Dominate the trail. Rebuild your mind.",
  "Embracing Growth and Action",
  "Every outdoor step leaves the old you behind.",
  "Eyes forward. Feet moving. Never look back.",
  "Forward Momentum",
  "Great things never came from comfort zones.",
  "If it scares you, it might be a good thing to try.",
  "If you're not serious about changing your life, you'll find an excuse.",
  "Keep moving. Progress is a daily choice.",
  "Motion is lotion for stiff joints.",
  "Move gently. Do not let stiffness win.",
  "Nature rewards the version of you that shows up.",
  "Nothing changes if nothing changes.",
  "One step closer to your peak version.",
  "Out here, you build unstoppable discipline.",
  "Pain whispers, but action speaks louder.",
  "Push Through the Pain",
  "Put on a jacket. Own the weather.",
  "Rain is just water. Your skin is waterproof.",
  "Rain washes away the old excuses.",
  "Start small. Walk just to the mailbox.",
  "Step outside. The storm will wait.",
  "Sweat out the old. Breathe in the new.",
  "The couch is dry, but growth is outside.",
  "The fresh air is waiting for the new you.",
  "The pavement does not care about the weather.",
  "We can't become what we need to be by remaining what we are.",
  "You are stronger than the cold wind.",
  "You don't have to be great to start, but you have to start to be great.",
  "You will never change your life until you change something you do daily.",
  "You're not starting over. You're starting wiser.",
  "Your future self is thanking you right now.",
];
